<a href="https://colab.research.google.com/github/pranitha2144/Internship-iith/blob/Resnet/resnet50implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import os
import time
from keras.applications import ResNet50
from keras.preprocessing import image
from keras.layers import GlobalAveragePooling2D,Dense, Dropout,Activation,Flatten

from keras.applications.imagenet_utils import preprocess_input
from keras.layers import Input
from keras.models import Model
from keras.utils import np_utils
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [3]:
img_path='/content/drive/My Drive/data/grade0/grade0-001.jpg'
img=image.load_img(img_path,target_size=(224,224))
x=image.img_to_array(img)
print(x.shape)
x=np.expand_dims(x,axis=0)
print(x.shape)
x=preprocess_input(x)
print(x.shape)

(224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)


In [4]:
data_path='/content/drive/My Drive/data'
data_dir_list=os.listdir(data_path)
img_data_list=[]
for dataset in data_dir_list:
  img_list=os.listdir(data_path+'/'+dataset)
  print('loaded images of dataset '+'{}\n'.format(dataset))
  for img in img_list:
    img_path=data_path+'/'+dataset+'/'+img
    img=image.load_img(img_path,target_size=(224,224))
    x=image.img_to_array(img)
    x=np.expand_dims(x,axis=0)
    x=preprocess_input(x)
    print(x.shape)
    img_data_list.append(x)



loaded images of dataset grade1

(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3

In [5]:
img_data=np.array(img_data_list)
print(img_data.shape)
img_data=np.rollaxis(img_data,1,0)
print(img_data.shape)
img_data=img_data[0]
print(img_data.shape)

(1000, 1, 224, 224, 3)
(1, 1000, 224, 224, 3)
(1000, 224, 224, 3)


In [0]:
num_classes=4
no_of_samples=img_data.shape[0]
labels = np.ones((no_of_samples,),dtype='int64')

In [8]:
labels[0:250]=0
labels[250:500]=1
labels[500:750]=2
labels[750:]=3
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [0]:
names=['grade1','grade0','grade2','grade3']

In [10]:
Y=np_utils.to_categorical(labels,num_classes)
Y

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [0]:
x,y=shuffle(img_data,Y,random_state=2)

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [13]:
print(X_train.shape)
print(Y_train.shape)
print(Y_test.shape)
print(X_test.shape)

(800, 224, 224, 3)
(800, 4)
(200, 4)
(200, 224, 224, 3)


Training custom resnet model

In [14]:
image_input=Input(shape=[224,224,3])
model=ResNet50(input_tensor=image_input,include_top=True,weights='imagenet')

102858752/102853048 [==============================] - 7s 0us/step


In [15]:
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
___________________________________________________________________________________________

In [16]:
last_layer=model.get_layer('avg_pool').output
#dropout=Dropout(0.5)(last_layer)
out=Dense(num_classes,activation='softmax',name='output_layer')(last_layer)
custom_resnet_model=Model(inputs=image_input,outputs=out)
custom_resnet_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
____________________________________________________________________________________________

In [17]:
for layer in custom_resnet_model.layers[:-1]:
  layer.trainable=False
#custom_resnet_model.layers[-2].trainable=True
custom_resnet_model.layers[-1].trainable

True

In [18]:
custom_resnet_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 112, 112, 64) 256         conv1[0][0]                      
____________________________________________________________________________________________

In [0]:
custom_resnet_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [0]:
from keras.preprocessing.image import ImageDataGenerator

In [0]:
datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=20,
        shear_range=0.2,
        zoom_range=0.2,
        width_shift_range=0.2,
        height_shift_range=0.2,
        fill_mode="nearest",
        horizontal_flip=True,vertical_flip=True,validation_split=0.2)

In [0]:
training_set = datagen.flow_from_directory(
        '/content/drive/My Drive/data',
        target_size=(224, 224),
        shuffle=True,
        subset="training",
        batch_size=32,
        class_mode='categorical')

Found 800 images belonging to 4 classes.


In [0]:
test_set = datagen.flow_from_directory(
        '/content/drive/My Drive/data',
        target_size=(224, 224),
        shuffle=True,
        subset="validation",
        batch_size=32,)

Found 200 images belonging to 4 classes.


In [20]:
t=time.time()
hist=custom_resnet_model.fit(X_train,Y_train,epochs=12,verbose=1,validation_split=0.2,shuffle=True,validation_data=(X_test,Y_test))
print("training time is %s"%(t-time.time()))

Train on 800 samples, validate on 200 samples
Epoch 1/12
800/800 [==============================] - 179s 224ms/step - loss: 0.7852 - accuracy: 0.6637 - val_loss: 1.4718 - val_accuracy: 0.3500
Epoch 2/12
800/800 [==============================] - 177s 221ms/step - loss: 0.4484 - accuracy: 0.8125 - val_loss: 1.5148 - val_accuracy: 0.3650
Epoch 3/12
800/800 [==============================] - 179s 224ms/step - loss: 0.3587 - accuracy: 0.8687 - val_loss: 1.5339 - val_accuracy: 0.3650
Epoch 4/12
800/800 [==============================] - 179s 224ms/step - loss: 0.3340 - accuracy: 0.8612 - val_loss: 1.6764 - val_accuracy: 0.3750
Epoch 5/12
800/800 [==============================] - 182s 227ms/step - loss: 0.2850 - accuracy: 0.8950 - val_loss: 1.9935 - val_accuracy: 0.3550
Epoch 6/12
800/800 [==============================] - 181s 226ms/step - loss: 0.2573 - accuracy: 0.9025 - val_loss: 2.5107 - val_accuracy: 0.3650
Epoch 7/12
800/800 [==============================] - 182s 227ms/step - loss: 

In [25]:
img_path='/content/drive/My Drive/data/grade0/grade0-100.jpg'
img=image.load_img(img_path,target_size=(224,224))
inp=image.img_to_array(img)
print(inp.shape)
inp=np.expand_dims(inp,axis=0)
print(inp.shape)
inp=preprocess_input(inp)
print(inp.shape)
custom_resnet_model.predict(inp)


(224, 224, 3)
(1, 224, 224, 3)
(1, 224, 224, 3)


array([[1.2736732e-01, 6.0579759e-01, 3.9528491e-05, 2.6679555e-01]],
      dtype=float32)